# Generated by Django 4.1.4 on 2022-12-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file_pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
